language: cpp

before_install:
  - echo "START"
  - sudo apt-get update
  - sudo apt-get install build-essential
  - ./opencv.sh

before_script:
  - chmod +x runner.sh
  - chmox +x opencv.sh

install: make get-deps
# install: true
# make && make test

compiler:
  - clang++
  - g++

script: "./runner.sh"


# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable

notifications:
  email:
    - wjuma@students.usiu.ac.ke
  on_success: change
  on_failure: always

