language: cpp

before_install:
  - echo "START"

before_script:
  - chmod +x runner.sh

install: make get-deps

compiler:
  - clang++
  - g++

script: "./runner.sh"


# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - development

notifications:
  email:
    - wjuma@students.usiu.ac.ke
  on_success: change
  on_failure: always

